audio:
  n_fft: 1200
  num_freq: 601 # n_fft//2 + 1
  sample_rate: 16000
  hop_length: 160
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  preemphasis: 0.97
  power: 0.30
---
model:
  lstm_dim: 400
  fc1_dim: 600
  fc2_dim: 601 # num_freq
---
data:
  libri_dir: 'datasets/LibriSpeech'
  vctk_dir: 'datasets/VCTK-Corpus'
  vin_dir: 'datasets/VinBigdata'
  voxceleb1_dir: 'datasets/VoxCeleb1'
  voxceleb2_dir: 'datasets/VoxCeleb2'
  zalo_dir: 'datasets/ZaloAI2020'
  audio_len: 3.0
---
train:
  batch_size: 2
  num_workers: 2
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 1
  grad_accumulate: 12
  checkpoint_interval: 3000
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
embedder: # d-vector embedder. don't fix it!
  num_mels: 40
  n_fft: 512
  emb_dim: 256
  lstm_hidden: 768
  lstm_layers: 3
  window: 80
  stride: 40
